title: Bespoke Tone
description: Helping photographers thrive.
baseurl: ""
url: "https://bespoketone.com"

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default
